### PR TITLE
use quoted identifiers on loading fixtures

### PR DESCRIPTION
**Pull request by tufanbarisyildirim**
insert query generator function should quote identifiers to prevent syntax errors in case a db developers use a reserved keyword as column/table name.

### CODE REVIEW

**Comment by tufanbarisyildirim** [comment]
@markbates could you please review this today if possible?

**Comment by markbates** [comment]
This PR has been open for less than 24 hours, I’ve been traveling all weekend, and it was my birthday. Please allow for some time. Someone, not necessarily me, will review your PR soon. Please give us time. Thank you.

**Comment by tufanbarisyildirim** [comment]
Oh we are born in same day! Happy birthday man! I just wanted to pull it on production with those changes, without doing it manually :) Enjoy your birthday, no worries, thanks!

**Comment by tufanbarisyildirim** [comment]
> Can you please add a test for this? Thank you. (and happy birthday! 🎂)

Since I thought it is tested in db context and this line already does assertion (https://github.com/gobuffalo/suite/blob/master/model.go#L60) I didn't do anything extra and a buffalo test already passes it (No error after db execution, actually my fixtures fails without it). Or you want me to separate query generator from the loader function and prove that it generates a correct sql before it runs? Or one more option, I can just change one of models to use a reserved keyword as a column name.

**Comment by markbates** [comment]
This still needs tests. 

What happens if this isn't there? I don't know. A test should show me what this changing is doing.

I don't have any idea what happens when this code runs, nor do I have trust that it won't break behavior. 

A test should answer those questions and If I revert the changes in the code, then the new test to should fail to prove that the changes work.

When are there tests, I will happily review this again. Thanks.

**Pull request closed without merging**
