### PR TITLE
use httptest instead of willie

### PR DESCRIPTION
**Pull request by sio4**
Use `httptest` instead of `willie`, related to #15

### CODE REVIEW

**Comment by markbates** [comment]
@sio4 I think the test was failing because of an old setup on travis we didn't need. I fixed it in `master` can you update your branch to see if that fixes the problem? Thanks!

**Comment by sio4** [comment]
Oops! I updated my branch with rebased commit, but the Travis-CI is disappeared!

**Comment by sio4** [comment]
Oh, I added one more commit and it runs!

**Comment by markbates** [comment]
Yay! Thanks!

**Comment by sio4** [comment]
You're welcome, Thanks so much!

**Pull request merged**
